config/routes.rb
OfficeTreats::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]

  root to: 'static_pages#home'
  match "/home_top" => "static_pages#home_top"
  match "/home_old" => "static_pages#home_old"

  match "/up" => "microposts#up"
  match "/down" => "microposts#down"
  match "/switch_to_up" => "microposts#switch_to_up"
  match "/switch_to_down" => "microposts#switch_to_down"

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/views/shared/_comment.html.erb
<li class="a_comment">
	<%= link_to comment.user.name, comment.user %>: <%= comment.text %>
	<% if current_user?(comment.user) %>
            <%= link_to image_tag("delete_static.png", :class => "delete_comment_img"), comment, method: :delete,
                                             data: { confirm: "You sure?" },
                                             title: comment.text, class: "delete_comment" %>
    <% end %>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
  	<% post_number=0 %>
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<span class="item">
  <li id="<%= feed_item.id %>">

    <% post_upvoted = false %>
    <% post_downvoted = false %>
    <% @arr_ups.each do |i| %>
      <% if i==feed_item.id %>
        <% post_upvoted=true %>
        <% break %>
      <% end %>
    <% end %>
    <% if !post_upvoted %>
      <% @arr_downs.each do |i| %>
        <% if i==feed_item.id %>
          <% post_downvoted=true %>
          <% break %>
        <% end %>
      <% end %>
    <% end %>
    <span class="item_without_comments">
      <span class="item_left">
        <span class="rating ignore">
          <% if feed_item.user.id == current_user.id %>
            <b>+</b></br>
            <%= feed_item.rating %></br>
            -
          <% else %>
            <% if !post_upvoted && !post_downvoted %>
              <%= link_to "+", up_path(:postID => feed_item, :pflag => params[:pflag]) %></br>
              <%= feed_item.rating %></br>
              <%= link_to "-", down_path(:postID => feed_item, :pflag => params[:pflag]) %>
            <% end %>
            <% if post_upvoted %>
              <b>+</b></br>
              <%= feed_item.rating %></br>
              <%= link_to "-", switch_to_down_path(:postID => feed_item, :pflag => params[:pflag]) %>
            <% end %>
            <% if post_downvoted %>
              <%= link_to "+", switch_to_up_path(:postID => feed_item, :pflag => params[:pflag]) %></br>
              <%= feed_item.rating %></br>
              <b>-</b>
            <% end %>
          <% end %>
        </span>
        <span class="ignore">
        <%= link_to gravatar_for(feed_item.user), feed_item.user %>
        </span>
      </span>
      <span clase="item_right">
        <span class="user ingore">
          <%= link_to feed_item.user.name, feed_item.user %>
        </span>
        <span class="content">
          <span class="content_text">
          <%= feed_item.content %>
          </span>
          <%= image_tag feed_item.image_url, class: "content_image ignore" if feed_item.image? %>
        </span>
        <span class="post_info">
          <span class="timestamp">
            Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
          </span>
          <% if current_user?(feed_item.user) %>
            <%= link_to "delete", feed_item, method: :delete,
                                             data: { confirm: "You sure?" },
                                             title: feed_item.content, class: "delete ignore" %>
          <% end %>
        </span>
      </span>
    </span>
        <div class="comments_section ignore">
          <%= form_for(Comment.new) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <div class="field">
              <span class="comment_input" %>
              <%= f.text_field :text, placeholder: "Comment...", :class => "comment_text_input" %>
              </span>
              <%= f.hidden_field :micropost_id, :value => feed_item.id %>
            </div>
            <%= f.submit "Post", class: "btn comment_post_btn" %>
          <% end %>
          <div class="comments">
            <% if @comments!=nil %>
              <ol class="replies">
                <%= render partial: 'shared/comment', collection: @comments.where(:micropost_id => feed_item.id) %>
              </ol>
            <% end %>
          </div>
        </div><br />
  </li>
</span>

app/views/shared/_home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="span8">
      <nav>
        <ul class="nav nav-pills">
          <% if signed_in? %>
            <% if @post_flag==0 %>
              <li class="active"><%= link_to "New Posts", root_path %></li>
            <% else %>
              <li><%= link_to "New Posts", root_path %></li>
            <% end %>

            <% if @post_flag==1 %>
              <li class="active"><%= link_to "Top Posts", home_top_path %></li>
            <% else %>
              <li><%= link_to "Top Posts", home_top_path %></li>
            <% end %>

            <% if @post_flag==2 %>
              <li class="active"><%= link_to "Old Posts", home_old_path %></li>
            <% else %>
              <li><%= link_to "Old Posts", home_old_path %></li>
            <% end %>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
      <%= render 'shared/feed' %>
    </div>
  </div>  
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to the Office Treats</h1>

    <h2>
      This is the home page for the
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
    </h2>

    <%= link_to "Sign up now!", signup_path, 
                                class: "btn btn-large btn-primary" %>
  </div>

  <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
<% end %> 

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost, :html => {:multipart => true} do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>

    <%= f.file_field :image %>
    <%= f.text_field :remote_image_url, placeholder: "Or image URL"  %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>